import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local"
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const nohemi = localFont({
  src: './fonts/Nohemi-VF.ttf',
  display: 'swap',
  variable: '--font-nohemi'
})

const timesnew = localFont({
  src: './fonts/TIMESI.ttf',
  display: 'swap',
  variable: '--font-times'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${nohemi.variable} ${timesnew.variable}`}>
      <body className={` bg-bg-color ${nohemi.variable}`}>{children}</body>
    </html>
  );
}
